var appConstants = {
    SERVICE_ERROR : 'Something went wrong in backend. We are working hard to resolve.',
    WSDL_GENERATE_FAILED : 'Failed to generate WSDL. Please try after sometime.',
    WSDL_FILE_LOC : './server/data/SOAP-WSDL.wsdl',
    FILENAME : 'SOAP-WSDL.wsdl',
    ROOT : 'wsdl:definitions',
    XMLNS_WSDL : 'http://schemas.xmlsoap.org/wsdl/',
    XMLNS_SOAP : 'http://schemas.xmlsoap.org/wsdl/soap/',
    XMLNS_TNS : 'http://service.lfg.com/',
    XMLNS_BONS2 : 'http://service.lfg.com/',
    XMLNS_XSD : 'http://www.w3.org/2001/XMLSchema',
    TRANSPORT : 'http://schemas.xmlsoap.org/soap/http',
    WSDL_TYPES : 'wsdl:types',
    XSD_SCHEMA : 'xsd:schema',
    XSD_ELEMENT : 'xsd:element',
    XSD_COMPLEX_TYPE : 'xsd:complexType',
    XSD_SEQUENCE : 'xsd:sequence',
    WSDL_MESSAGE : 'wsdl:message',
    WSDL_PART : 'wsdl:part',
    WSDL_PORT_TYPE : 'wsdl:portType',
    WSDL_OPERATION : 'wsdl:operation',
    WSDL_IN : 'wsdl:input',
    WSDL_OU : 'wsdl:output',
    WSDL_BINDING : 'wsdl:binding',
    WSDL_PORT : 'wsdl:port',
    WSDL_SERVICE : 'wsdl:service',
    SOAP_ADDRESS : 'soap:address',
    SOAP_OPERATION : 'soap:operation',
    SOAP_BODY : 'soap:body'
}

module.exports = appConstants;